name: EMHASS Runtime Only
version: "1.2.1"
slug: emhass_runtime_only
description: "EMHASS server without Home Assistant fetching (runtime-only)."
arch:
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
init: false
ingress: false
ports:
  "5000/tcp": 5000
map:
  - share:rw
  - data:rw


options:
  data_path: /share
  log_level: INFO
  hass_url: empty
  hass_token: empty
  use_websocket: false

schema:
  data_path: str
  log_level: str
  hass_url: str
  hass_token: str
  use_websocket: bool

hassio_api: true
homeassistant_api: true
auth_api: true

